[start]
command: /usr/local/etc/rc.d/adguardhome start
parameters:
type: script
message: Start AdGuard Home Service

[stop]
command: /usr/local/etc/rc.d/adguardhome stop
parameters:
type: script
message: Stop AdGuard Home Service

[restart]
command: /usr/local/etc/rc.d/adguardhome restart
parameters:
type: script
message: Restart AdGuard Home Service

[status]
command: /usr/local/etc/rc.d/adguardhome status;exit 0
parameters:
type: script_output
message: Request AdGuard Home Status

[apply]
command: /usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/AdGuardHome/apply_config.php
parameters:
type: script
message: Apply AdGuard Home managed configuration
