PLUGIN_NAME=		adguardhome
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=		6
PLUGIN_COMMENT=		Network-wide ads & trackers blocking DNS server
PLUGIN_DEPENDS=		adguardhome
PLUGIN_MAINTAINER=	github@daniel-krebs.net
PLUGIN_WWW=		https://github.com/AdguardTeam/AdGuardHome

.include "../../Mk/plugins.mk"
